@startuml
class "CFS-score"{
   score : Integer, tall 1-9
   tidspunkt : Datetime
   notat: string, tekst med\n utfyllende informasjon
}

class Pasient {
   Navn : HumanName
   Identifikator : FNR, DNR, HNR
   ...
}

Class Helsepersonell {
   Navn : HumanName
   Identifikator : HPR, FNR
   Kategori helsepersonell : code
}

Class AnsvarligVirksomhet {
   Navn : Navn på virksomhet
   Identifikator : orgnr, RESHid
}

<> diamond

"CFS-score" --> Pasient :subjekt
"CFS-score" -- diamond :forfatter
diamond --> Helsepersonell
diamond --> Pasient
"CFS-score" --> AnsvarligVirksomhet :ansvarlig\nvirksomhet

@enduml