@startuml
   !include <archimate/Archimate>
   Motivation_Stakeholder(kommune, "Kommune")
   Motivation_Stakeholder(sykehus, "Sykehus")
   Motivation_Stakeholder(innbygger, "Innbygger")
   Motivation_Stakeholder(fastlege, "Fastlege")

   Motivation_Value(samhandling, "Samhandlingsverktøy")
   Motivation_Value(felles, "Felles forståelse\nav pasienten")
   Motivation_Value(identifisere, "Identifisere pasienter\nmed skrøpelighet")
   Motivation_Value(ressurser, "Ressursfordeling")
   Motivation_Value(beslutning, "Beslutningsstøtte")
   Motivation_Value(behandling, "Behandlingsstøtte")
   Motivation_Value(forebygge, "Forebygge funksjonsfall")

   Rel_Association(kommune, samhandling)
   Rel_Association(sykehus, samhandling)
   Rel_Association(fastlege, samhandling)

   Rel_Association(fastlege, ressurser)
   Rel_Association(kommune, ressurser)
   Rel_Association(sykehus, ressurser)

   Rel_Aggregation(ressurser, beslutning)
   Rel_Aggregation(ressurser, behandling)

   Rel_Association(fastlege, felles)
   Rel_Association(kommune, felles)
   Rel_Association(sykehus, felles)

   Rel_Specialization(samhandling, felles)
   Rel_Specialization(samhandling, identifisere)
   Rel_Specialization(samhandling, ressurser)

   Rel_Association(innbygger, forebygge)
   Rel_Association(fastlege, forebygge)
   Rel_Association(kommune, forebygge)
@enduml