@startuml
FHIRClient --> PMD: BatchBundle (fullUrl1, fullUrl2) 
PMD --> PMDBackend: Store1
PMDBackend --> PMD: serverid1
PMD --> PMDBackend: Store2
PMDBackend --> PMDBackend: FEIL
PMDBackend --> PMD: serverid2
PMD --> FHIRClient: BatchBundle (fullUrl1, fullUrl2, serverid1, FEIL)
@enduml