@startuml
FHIRClient --> PMD: BatchBundle (fullUrl1, fullUrl2) 
PMD --> PMDBackend: Store1
PMDBackend --> PMD: serverid1
PMD --> PMDBackend: Store2
PMDBackend --> PMDBackend: FEIL
PMDBackend --> PMD: errormsg
PMD --> FHIRClient: BatchResponseBundle (fullUrl1, serverid1, fullUrl2, errormsg)
@enduml